CREATE SCHEMA IF NOT EXISTS WHITEBOARD;

CREATE TABLE IF NOT EXISTS WHITEBOARD.ROOM(
    id SERIAL PRIMARY KEY NOT NULL,
    created TIMESTAMP NOT NULL,
    updated TIMESTAMP NOT NULL default CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS WHITEBOARD.CONTENT_TYPE (
    id SERIAL PRIMARY KEY NOT NULL,
    type TEXT,
    created TIMESTAMP NOT NULL,
    updated TIMESTAMP NOT NULL default CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS WHITEBOARD.LINA_USER (
    id SERIAL PRIMARY KEY NOT NULL,
    username TEXT NOT NULL,
    created TIMESTAMP NOT NULL,
    updated TIMESTAMP NOT NULL default CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS WHITEBOARD.BOARD (
    id SERIAL PRIMARY KEY NOT NULL,
    room_id INTEGER REFERENCES WHITEBOARD.ROOM(id),
    content_type_id INTEGER REFERENCES WHITEBOARD.CONTENT_TYPE(id),
    commands TEXT,
    created TIMESTAMP NOT NULL,
    updated TIMESTAMP NOT NULL default CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS WHITEBOARD.SAMPLE_COMMAND (
    id SERIAL PRIMARY KEY NOT NULL,
    content_type_id INTEGER REFERENCES WHITEBOARD.CONTENT_TYPE(id),
    commands TEXT,
    created TIMESTAMP NOT NULL,
    updated TIMESTAMP NOT NULL default CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS WHITEBOARD.ROOM_USERS (
    id SERIAL PRIMARY KEY NOT NULL,
    lina_user_id INTEGER REFERENCES WHITEBOARD.LINA_USER(id),
    room_id INTEGER REFERENCES WHITEBOARD.ROOM(id),
    created TIMESTAMP NOT NULL,
    updated TIMESTAMP NOT NULL default CURRENT_TIMESTAMP
);