const CONSTANTS = {
	COMMANDS_CONTAINER_ID: 'commands-container',
	COMMANDS_ACE_EDITOR_CONTAINER: 'commandsAceEditorContainer',
	SAMPLE_COMMANDS_ID: 'sample-commands',
	DISPLAY_SIZE_SMALL: 'display_size_small',
	DISPLAY_SIZE_MEDIUM: 'display_size_medium',
	DISPLAY_SIZE_LARGE: 'dispaly_size_large',

	RTC_MESSAGE_TYPES: {
		ADD_BOARD: 'ADD_BOARD',
		RUN_COMMANDS: 'RUN_COMMANDS',
		REMOVE_BOARD: 'REMOVE_BOARD'
	},
	WS_KEEP_ALIVE_MESSAGE: 'WS_KEEP_ALIVE_MESSAGE',
	WS_KEEP_ALIVE_INTERVAL_IN_MS: 10000
};

export { CONSTANTS };
